FORMAT: 1A
HOST: https://reklapp-server.herokuapp.com/webapi

# REKLAPP-server

REKLAPP-server is a server for REKLAPP application.

## Ping [/ping]

### Ping Service [GET]

Returns html status code 200, if the server is alive.

+ Response 200 (application/json)


## User's Money [/users/{mobile_number}/money]

### Get Money for User [GET]

Returns money user have on balance in GEL.

+ Parameter
    + mobile_number (required, string, `555555555`)
    String returned in Location header field.
    
+ Response 200 (application/json)

        [
            {
                "money": "1.00"
            }
        ]

## Random Advertisment [/users/{mobile_number}/advertisments/random]

### Get Random Advertisment [GET]

Returns video link.

+ Parameter
    + mobile_number (required, string, `555555555`)
    String returned in Location header field.
    

+ Response 200 (application/json)

        [
            {
                "link": "https://ia600201.us.archive.org/22/items/ksnn_compilation_master_the_internet/ksnn_compilation_master_the_internet_512kb.mp4"
            }
        ]
        
        
## Custom Advertisment [/users/{mobile_number}/advertisments/custom/{custom_advertisment_string}]

### Get Custom Advertisment [GET]

Returns video link.

+ Parameter
    + mobile_number (required, string, `555555555`)
    String returned in Location header field.
    

+ Response 200 (application/json)

        [
            {
                "link": "https://ia600201.us.archive.org/22/items/ksnn_compilation_master_the_internet/ksnn_compilation_master_the_internet_512kb.mp4"
            }
        ]
        
        
## User Data [/users]

### Add User [PUT]

Adds user to server database.

+ Request (application/json)

        {
            "name": "თორნიკე",
            "surname": "მანძულაშვილი",
            "pin": "01019080139",
            "country" : "საქართველო",
            "city" : "თბილისი",
            "street_address" : "თემქა კაროჩე",
            "mobile_number" : "555555555",
            "sex" : "male",
            "birthdate" : "19.01.1995",
            "relationship" : "single",
            "number_of_children" : "0",
            "average_monthly_income" : "10000",
            "email" : "tornikeman@gmail.com"
        }
        
+ Response 200 (application/json)
        
+ Request (application/json)

        {
            "name": "თორნიკე",
            "surname": "მანძულაშვილი",
            "pin": "01019080133232329",
            "country" : "საქართველო",
            "city" : "თბილისი",
            "street_address" : "თემქა კაროჩე",
            "mobile_number" : "555555555",
            "sex" : "male",
            "birthdate" : "19.01.1995",
            "relationship" : "single",
            "number_of_children" : "0",
            "average_monthly_income" : "10000",
            "email" : "tornikeman@gmail.com"
        }


+ Response 400 (application/json)

        [
            {
                "problem": "რამხელა პინია რა არი ეგ?!"
            }
        ]
        
        
### Update User [POST]

Updates user in server database.

+ Request (application/json)

        {
            "name": "თორნიკე",
            "surname": "მანძულაშვილი",
            "pin": "01019080139",
            "country" : "საქართველო",
            "city" : "თბილისი",
            "street_address" : "თემქა კაროჩე",
            "mobile_number" : "555555555",
            "sex" : "male",
            "birthdate" : "19.01.1995",
            "relationship" : "single",
            "number_of_children" : "0",
            "average_monthly_income" : "10000",
            "email" : "tornikeman@gmail.com"
            "old_mobile_number" : "555555555"
        }
        
+ Response 200 (application/json)
        
## Transfer Money [/users/{mobile_number}/transfer]

### Transfer money [POST]

Transfers money to your balance.

+ Parameter
    + mobile_number (required, string, `555555555`)
    String returned in Location header field.

+ Request (application/json)

        {
            "address" : "555555555",
            "amound" : "1.0"
        }
        
+ Response 200 (application/json)