FORMAT: 1A
HOST: https://reklapp-server.herokuapp.com/webapi

# REKLAPP-server

REKLAPP-server is a server for REKLAPP application.

## Ping [/ping]

### Ping Service [GET]

Returns html status code 200, if the server is alive.

+ Response 200 (application/json)


## User's Money [/users/{mobile_number}/money]

### Get Money for User [GET]

Returns money user have on balance in GEL.

+ Parameter
    + mobile_number (required, string, `555555555`)
    String returned in Location header field.
    
+ Response 200 (application/json)

        {
            "money": 1.0
        }

## Random Advertisment [/users/{mobile_number}/advertisments/random]

### Get Random Advertisment [GET]

Returns video link.

+ Parameter
    + mobile_number (required, string, `555555555`)
    String returned in Location header field.
    

+ Response 200 (application/json)

        {
            "status": "Request completed.",
            "pair_id": 4,
            "link": "https://www.youtube.com/watch?v=WxO9cKtGi1s",
            "company": "freeuni",
            "product": "good education",
            "description": "good uni",
            "view_gain": 0.01
        }
        
        
## Custom Advertisment [/users/{mobile_number}/advertisments/custom/{custom_advertisment_string}]
        
        
## User Data [/users]

### Update/Add User [PUT]

Updates user in server database, or adds if not present.

+ Request (application/json)

        {
            "name": "თორნიკე",
            "surname": "მანძულაშვილი",
            "pin": "01019080139",
            "country" : "საქართველო",
            "city" : "თბილისი",
            "password" : "პაროლი",
            "street_address" : "თემქა კაროჩე",
            "mobile_number" : "555555555",
            "sex" : "male",
            "birthdate" : "1995-01-19",
            "relationship" : "single",
            "number_of_children" : 0,
            "average_monthly_income" : 10000,
            "email" : "tornikeman@gmail.com",
            "old_mobile_number" : "555555555",
            "money" : 1.0
        }
        
+ Response 200 (application/json)

        {
            "problem": "Update Completed."
        }
        
+ Request (application/json)

        {
            "name": "თორნიკე",
            "surname": "მანძულაშვილი",
            "pin": "01019080133232329",
            "country" : "საქართველო",
            "city" : "თბილისი",
            "street_address" : "თემქა კაროჩე",
            "password" : "პაროლი",
            "mobile_number" : "555555555",
            "sex" : "male",
            "birthdate" : "1995-01-19",
            "relationship" : "single",
            "number_of_children" : 0,
            "average_monthly_income" : 10000,
            "email" : "tornikeman@gmail.com",
            "old_mobile_number" : "555555555",
            "money" : 1.0
        }

+ Response 200 (application/json)

        {
            "problem": "რამხელა პინია რა არი ეგ?!"
        }
        
## Mobile/Bank Transfer [/users/{mobile_number}/transfer/{address}]

### Transfer money [POST]

Transfers money to your Mobile/Bank balance.

+ Parameter
    + mobile_number (required, string, `555555555`)
    String returned in Location header field.
    
    + address (required, string, `555555555`)
    String returned in Location header field.

+ Request (application/json)

        {
            "amount" : 1.0
        }
        
+ Response 200 (application/json)

        {
            "problem": "Transfer Completed."
        }